name: discord_interactions_example
description: An example project for the discord_interactions package that runs on Google Cloud Run
version: 1.0.0
publish_to: none
homepage: https://github.com/Rexios80/discord_interactions/tree/master/example

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  functions_framework: ^0.4.1
  enum_to_string: ^2.0.1
  shelf: ^1.3.0
  discord_interactions:
    path: ../

dev_dependencies:
  rexios_lints: ^3.0.0
  build_runner: ^2.1.5
  functions_framework_builder: ^0.4.4
