name: discord_interactions
description: A webhook-based Discord Interactions client. Made with serverless deployment in mind.
version: 0.0.13
homepage: https://github.com/Rexios80/discord_interactions

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  json_annotation: ^4.7.0
  dio: ^4.0.3
  pinenacl: ^0.5.1
  convert: ^3.0.1
  collection: ^1.15.0
  dio_response_validator: ^0.2.0

dev_dependencies:
  rexios_lints: ^4.0.0
  test: ^1.16.0
  build_runner: ^2.1.5
  json_serializable: ^6.0.1
  yaml: ^3.1.0

  # dart run import_sorter:main
  import_sorter: ^4.6.0

  # dependencies for example
  functions_framework: ^0.4.1

  # dependencies for tests
  web_socket_channel: ^2.1.0
