name: discord_interactions
description: A webhook-based Discord Interactions client. Made with serverless deployment in mind.
version: 0.0.1
homepage: https://github.com/Rexios80/discord_interactions

environment:
  sdk: '>=2.14.4 <3.0.0'


dependencies:
  json_annotation: ^4.3.0
  dio:
    git: 
      url: https://github.com/Rexios80/dio.git
      ref: d6df21b7cb433db7ff9988bfcd691b249e1bab76
      path: dio
  pinenacl: ^0.3.3
  convert: ^3.0.1

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  build_runner: ^2.1.5
  json_serializable: ^6.0.1
  yaml: ^3.1.0

  # dart run import_sorter:main
  import_sorter: ^4.6.0

  # dependencies for example
  functions_framework: ^0.4.1
