name: discord_interactions
description: A http based Discord Interactions API client. Made for serverless deployment in mind.
version: 0.0.1
homepage: https://github.com/Rexios80/discord_interactions

environment:
  sdk: '>=2.14.4 <3.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
