name: discord_interactions
description: A http based Discord Interactions API client. Made with serverless deployment in mind.
version: 0.0.1
homepage: https://github.com/Rexios80/discord_interactions

environment:
  sdk: '>=2.14.4 <3.0.0'


dependencies:
  json_annotation: ^4.3.0
  dio: ^4.0.3

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  build_runner: ^2.1.5
  json_serializable: ^6.0.1
  yaml: ^3.1.0
